### ISSUE TITLE
Create a website design for Open CAESAR

### ISSUE THREAD

**Issue by melaasar** [opencaesar/opencaesar.github.io#2]
Open CAESAR needs to have a good web site design that allows:

- [ ] Posting documentation on Open CAESAR
- [ ] Blogging about Open CAESAR
- [ ] Posting about new releases of Open CAESAR
- [ ] Linking to the wikis of Open CAESR
- [ ] Posting the papers published on Open CAESAR
- [ ] Posting information about the contributors of Open CAESAR
- [ ] Have links to other pages for individual repositories

**Comment by iamatomo** [comment]
I'll get started on this today and we can chat at stand up on when I can get the deliverables up here to support the requirements.

**Comment by melaasar** [comment]
Moved the description of this issue to the Project https://github.com/orgs/open-caesar/projects/3

**Comment by mpnewcom** [comment]
Here's a WebLink to the completed static designs.
https://zpl.io/adpeD3L

**Comment by melaasar** [comment]
Maybe, we add (Fontawesome like) icons beside the points in the last section of the front page?

**Comment by mpnewcom** [comment]
For new requests like this, can we create a separate ticket (like yesterday's ticket for the multiple author on a blog post use case). I'd like to track new requests against the completed design system as individual tickets.

**Comment by melaasar** [comment]
This is done
