### ISSUE TITLE
Develop the Front End of the OpenCAESAR Community Site

### ISSUE THREAD

**Issue by mpnewcom** [opencaesar/opencaesar.github.io#6]
The OpenCAESAR Community Site will first bet set up as a static, front-end iteration in order to property QA the development implementation of the design.

**Homepage**
- [ ] [Desktop Specs](https://app.zeplin.io/project/5c87e0b8bd45880462bed52a/screen/5c8ae21f361d0e055111c7dc) 
- [ ] [Mobile Specs](https://app.zeplin.io/project/5c87e0b8bd45880462bed52a/screen/5c9d4939a1b13978ed722088) 

**Content Listing Page**
- [ ] [Desktop Specs](https://app.zeplin.io/project/5c87e0b8bd45880462bed52a/screen/5c8ae21c84704c0df40e46f0)
- [ ] [Mobile Specs](https://app.zeplin.io/project/5c87e0b8bd45880462bed52a/screen/5c8ae4122738d70533b3fb5f)

**Content Listing Page (Case Studies + Papers Variation)**
- [ ] [Desktop Specs](https://app.zeplin.io/project/5c87e0b8bd45880462bed52a/screen/5c9cf7699af3460569f5547c)
- [ ] [Mobile Specs](https://app.zeplin.io/project/5c87e0b8bd45880462bed52a/screen/5c9cf71b40d00405f5efabb0)

**Contributors Landing Page**
- [ ] [Desktop Specs](https://app.zeplin.io/project/5c87e0b8bd45880462bed52a/screen/5c9cf68d29ec4e062d8eaa61)
- [ ] [Mobile Specs](https://app.zeplin.io/project/5c87e0b8bd45880462bed52a/screen/5c9cf71cff87da691c6df00e)

**Contributors Detail Page**
- [ ] [Desktop Specs](https://app.zeplin.io/project/5c87e0b8bd45880462bed52a/screen/5c9cf60696545605b29bde98)
- [ ] [Mobile Specs](https://app.zeplin.io/project/5c87e0b8bd45880462bed52a/screen/5c9cf71bea57b00545aa544f)

**Download Page**
- [ ] [Desktop Specs](https://app.zeplin.io/project/5c87e0b8bd45880462bed52a/screen/5c9cf64dff87da691c6dd575)
- [ ] [Mobile Specs](https://app.zeplin.io/project/5c87e0b8bd45880462bed52a/screen/5c8ae4119663d72519358a45)

**Content Detail Page (Used for Blog Detail, Case Studies, and Papers)**
- [ ] [Desktop Specs](https://app.zeplin.io/project/5c87e0b8bd45880462bed52a/screen/5c87e14bb87cb83866a12695)
- [ ] [Mobile Specs](https://app.zeplin.io/project/5c87e0b8bd45880462bed52a/screen/5c8ae4123754f40dd0fff4de)

**Additional References**
- [Content Detail Page w/Additional Text Treatments](https://app.zeplin.io/project/5c87e0b8bd45880462bed52a/screen/5c892d53541a44392158c832)
- [Long Read Browser](https://app.zeplin.io/project/5c87e0b8bd45880462bed52a/screen/5c892d54028080195e6220c7)
- [Mobile Navigation](https://app.zeplin.io/project/5c87e0b8bd45880462bed52a/screen/5c8ae4106da6380593d64358)

**Comment by melaasar** [comment]
this is done
